In [2]:
import torch
from __future__ import print_function


In [7]:
#create tensor 5 by 3
x=torch.empty(5,3)
print(x)

tensor([[4.4600e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.6255e-43],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 1.4838e-41, 1.6115e-43],
        [1.5554e-43, 1.5975e-43, 1.4778e-36]])


In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9320, 0.2079, 0.5955],
        [0.0668, 0.0041, 0.8018],
        [0.3723, 0.7436, 0.0803],
        [0.4417, 0.5896, 0.4965],
        [0.6528, 0.2378, 0.8813]])


In [12]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
#torch from data
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      #to create tensor from old one
x = torch.randn_like(x, dtype=torch.float)   # to copy shpae of tensor

In [15]:
print(x.size())
#to rezize a tensor use view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([5, 3])


In [16]:
import numpy as np
#convert numpy to torch
a=np.array([5,3,5])
b=torch.from_numpy(a)
print(b)

tensor([5, 3, 5])


In [25]:
#to perform back prop you have to enable grad on vlaues and specify the one that get updated
x=torch.ones(2,2,requires_grad=True);
y=x+2
print(y)
print(x)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [26]:
#more operations to see how far it goes
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [22]:
#to turn existing tensor to use back prop
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)

False
True


In [27]:
#now to back prop
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [23]:
#we had diffrential of (x+2)^2 *3=3(x+2)^2
#z=3(x+2)^2
#out=z.mean=21
#diffrential do/dx=3/2(x+2)=9/2 at x=1 =4.5

None


In [ ]:
#to stop tracking gradients
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

In [28]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
